title: "Polarization of Opinions on COVID-19 Measures: Integrating Twitter and SurveyData"
description: >- # this means to ignore newlines until "baseurl:"
  Social Science Computer Review (SSCR)
# Build settings
remote_theme: socialcomplab/cayman
github:
  parent: https://socialcomplab.github.io/
